[language.javascript]
command = "typescript-language-server"
args = ["--stdio"]
synchronous_triggers = ["."]
synchronous_timeout_ms = 300
num_server_instances = 2
always_prefer = true
install = [["yarn", "global", "add", "javascript-typescript-langserver"]]

[language.typescript]
command = "typescript-language-server"
args = ["--stdio"]
num_server_instances = 2
synchronous_triggers = ["."]
synchronous_timeout_ms = 300
always_prefer = true
install = [["yarn", "global", "add", "javascript-typescript-langserver"]]

[language.vue]
command = "vls"
always_prefer = false
synchronous_triggers = ["."]
synchronous_timeout_ms = 300
args = []
num_server_instances = 2
install = [["yarn", "global", "add", "vue-language-server"]]

[language.html]
command = "html-languageserver"
args = ["--stdio"]
num_server_instances = 2
install = [["yarn", "global", "add", "vscode-html-languageserver-bin"]]

[language.css]
command = "css-languageserver"
args = ["--stdio"]
install = [["yarn", "global", "add", "vscode-css-languageserver-bin"]]

[language.sass]
command = "css-languageserver"
args = ["--stdio"]
install = [["yarn", "global", "add", "vscode-css-languageserver-bin"]]

[language.less]
command = "css-languageserver"
args = ["--stdio"]
install = [["yarn", "global", "add", "vscode-css-languageserver-bin"]]