[language.rust]
command = "rls"
install = [
  ["rustup", "update"],
  ["rustup", "component", "add", "rls-preview", "rust-analysis", "rust-src"],
]

[language.javascript]
command = "flow"
args = ["lsp"]
install = [["yarn", "global", "add", "flow-bin"]]

[language.html]
command = "html-languageserver"
args = ["--stdio"]
install = [["yarn", "global", "add", "vscode-html-languageserver-bin"]]

[language.ocaml]
command = "ocaml-language-server"
args = ["--stdio"]
install = [["yarn", "global", "add", "ocaml-language-server"]]

[language.python]
command = "pyls"
install = [["pip", "install", "python-language-server"]]

[language.cpp]
command = "cquery"
args = ["--init={\"cacheDirectory\": \"${project_root}/.cquery_cache\"}"]

[language.haskell]
command = "hie"
args = ["--lsp"]

[language.go]
command = "go-langserver"
args = ["-mode", "stdio", "-gocodecompletion"]
install = [["go", "get", "-u", "github.com/sourcegraph/go-langserver"]]

[language.bash]
command = "bash-language-server"
args = ["start"]

[language.dart]
command = "dart_language_server"
install = [["pub", "global", "activate", "dart_language_server"]]
